# 04-eth-parser -- see README.md.   make test | make lint | make wave | make clean
TESTS := eth_udp_parser:eth_udp_parser.sv:test_eth_udp_parser:
LINTS := eth_udp_parser:eth_udp_parser.sv:

include ../common/project.mk
